apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-xtqeymuy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-xtqeymuy 
  name: go-xtqeymuy
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-xtqeymuy
    weight: 100 
